[phases.setup]
nixPkgs = ["dotnet-sdk_8"]

[phases.install]
cmds = ["cd DailySchedule && dotnet restore"]

[phases.build]
cmds = ["cd DailySchedule && dotnet publish --no-restore -c Release -r linux-x64 -o out"]

[start]
cmd = "./DailySchedule/out/DailySchedule"
